### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by friedger** [friedger/clarity-stacking-pools#16]
pox-pools-1-cycle-v2:

- [x] should use pox-3
- [x] should prevent extending more than 1 cyle
- [x] should provide correct amount of locked stx per pool member per cycle
- [x] should extend using the same amount and avoid err-decrease-forbidden

pox-pool-self-service-v2:

- [x] should use pox-3
- [x] should prevent extending more than 1 cyle
- [x] should provide correct amount of locked stx per pool member per cycle
- [x] should extend using the same amount and avoid err-decrease-forbidden

**Comment by friedger** [comment]
Isn't a separate contract more convenient for each user option?

**Comment by yknl** [comment]
Then that means an additional contract call.

**Comment by friedger** [comment]
What would the signature look like? A key and value string that is stored in a map of  `{user: principal, key: (string-ascii 8)} (string-ascii 80)` ?

**Comment by yknl** [comment]
I think that could work.

**Comment by friedger** [comment]
Fix get-status-list for extended and increased users

**Comment by 2snEM6** [comment]
> What would the signature look like? An optional key and value string tuple that is stored in a map of `{user: principal, key: (string-ascii 8)} (string-ascii 80)` ?

This is a great idea

**Comment by 2snEM6** [comment]
Could be named "metadata" as it really is a meta. What about the size of it?

**Comment by friedger** [comment]
@2snEM6 What do you mean? Which size?

**Comment by friedger** [comment]
What are the keys you would use today?

Do we need a list of key values in `delegate-stx`?

**Comment by 2snEM6** [comment]
I meant the size of the ascii string @friedger

**Comment by friedger** [comment]
Also questions about updating, deleting, etc

**Comment by friedger** [comment]
deployed
